In [1]:
#!/usr/bin/env python
import pandas as pd
import numpy as np
import os

In [2]:
# working directory
workingDir = "C:/Users/rjame/Documents/WSWC Documents/MappingStatesDataToWaDE2.0/California/WaterAllocation/RawInputData"
os.chdir(workingDir)

In [3]:
# Input files
fileInput1 = "EWRIMS MASTER FLAT FILE DATA DICTIONARY DRAFT 1-17-20.xlsx" 

# output water sources
out_put = "watersources.csv"

In [4]:
##### WaDE columns

columns=['WaterSourceUUID', 'WaterSourceNativeID',	'WaterSourceName', 'WaterSourceTypeCV',
         'WaterQualityIndicatorCV',	'GNISFeatureNameCV', 'Geometry']

dtypesx = ['BigInt	NVarChar(250)	NVarChar(250)	NVarChar(250)	NVarChar(100)	NVarChar(100)',
           'NVarChar(250)	Geometry']

In [5]:
### target dataFrame

# TODO: assumes dtypes inferred from CO file
outdf100=pd.DataFrame(columns=columns)

In [6]:
print("Reading inputs...")

# sheet to read = "ewrims_flat_file"
df100 = pd.read_excel(fileInput1, header=0, sheet_name="ewrims_flat_file", skiprows=0, encoding = "ISO-8859-1") #, or alternatively encoding = "utf-8"

df100 = df100.drop_duplicates()   #
print (len(df100.index))

#df100 = df100.head(10000) #only runs first 100 lines for testing.

df100 = df100.replace(np.nan, '')
df100

Reading inputs...
57736

,WR_WATER_RIGHT_ID,APPLICATION_NUMBER,CERTIFICATE_ID,PERMIT_ID,LICENSE_ID,WATER_RIGHT_TYPE,WATER_RIGHT_STATUS,APPLICATION_NUMBER_PARTY,PWSS_ID,PRIORITY_DATE,...,PETITION_STATUS_TYPE,DATE_RECEIVED,DATE_COMPLETED,PET_LAST_UPDATE_DATE,NUM_OF_PETITIONS,ENF_CASE_NUMBER,ENF_CASE_START_DATE,ENF_CASE_CLOSURE_DATE,ENF_CASE_COUNTY,NUMBER_OF_ENFORCEMENT_CASE
0,0,,,,,Not Determined,,,,,...,,,,,,ENF03549,1573084800000000000,1577750400000000000,Santa Clara,98
1,1,T032025,,,,Temporary Permit,Cancelled,T032025,,,...,,,,,,,,,,0
2,2,A000016,41,30,41,Appropriative,Licensed,A000016,,,...,,,,,,,,,,0
3,3,A000018,2871,29,2871,Appropriative,Licensed,A000018,,,...,,,,,,,,,,0
4,4,A000023,1986,273,1986,Appropriative,Licensed,A000023,,,...,Pending,1578441600000000000,,1578564981000000000,34,,,,,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57731,73078,UN002198,,,,Not Determined,Active,UN002198,,,...,,,,,,,,,,0
57732,73088,UN002199,,,,Not Determined,Active,UN002199,,,...,,,,,,,,,,0
57733,73089,A033099,,,,Appropriative,Pending,A033099,,,...,,,,,,,,,,0
57734,73108,UN002200,,,,Not Determined,Active,UN002200,,,...,,,,,,,,,,0
57735,73109,UN002201,,,,Not Determined,Closed,UN002201,,,...,,,,,,,,,,0

In [7]:
list(df100.columns)

['WR_WATER_RIGHT_ID',
 'APPLICATION_NUMBER',
 'CERTIFICATE_ID',
 'PERMIT_ID',
 'LICENSE_ID',
 'WATER_RIGHT_TYPE',
 'WATER_RIGHT_STATUS',
 'APPLICATION_NUMBER_PARTY',
 'PWSS_ID',
 'PRIORITY_DATE',
 'RECEIPT_DATE',
 'REJECTION_DATE',
 'APPLICATION_RECD_DATE',
 'APPLICATION_ACCEPTANCE_DATE',
 'PROJECT_TYPE',
 'RECORD_SUMMARY',
 'INCOMPLETE_STATEMENT',
 'NUMBER_OF_PROTESTS',
 'AGENT_NAME',
 'AGENT_ENTITY_TYPE',
 'APPLICATION_PRIMARY_OWNER',
 'PRIMARY_OWNER_ENTITY_TYPE',
 'SUB_TYPE',
 'INI_REPORTED_DIV_AMOUNT',
 'INI_REPORTED_DIV_UNIT',
 'FACE_VALUE_AMOUNT',
 'FACE_VALUE_UNITS',
 'FEE_DUE',
 'FEE_RECEIVED',
 'APPL_FEE_AMOUNT',
 'APPL_FEE_AMT_RECD',
 'MAX_DD_APPL',
 'MAX_DD_UNITS',
 'MAX_DD_ANN',
 'MAX_STORAGE',
 'MAX_TAKEN_FROM_SOURCE',
 'YEAR_DIVERSION_COMMENCED',
 'MAX_BENEFICIALLY_USED',
 'SUPPLEMENTAL_STATEMENT_CYCLE',
 'TYPE_OF_DIVERSION_FACILITY',
 'QUANTITY_OF_WATER_DIVERTED',
 'QOW_DIVERTED_UNIT',
 'QUANTITY_MEASUREMENT_YEAR',
 'MAX_RATE_OF_DIVERSION',
 'MAX_RATE_OF_DIV_UNIT',
 'RECENT_WATER_USE_MIN',
 'WATER_USE_MIN_UNIT',
 'RECENT_WATER_USE_MAX',
 'WATER_USE_MAX_UNIT',
 'REQUEST_FOR_REVOCATION_RECD',
 'NUM_COMMENTS',
 'NUM_ATTACHMENTS',
 'LAST_UPDATE_DATE',
 'STATE_WELL_NUMBER',
 'DRILLED_WELL_YEAR',
 'SURFACE_WATER_DIVERSIONS',
 'DEPTH_OF_WELL',
 'RELATIONSHIP_TYPE',
 'PARTY_ID',
 'EFFECTIVE_FROM_DATE',
 'EFFECTIVE_TO_DATE',
 'PRIMARY_OWNER_NAME',
 'PRIMARY_OWNER_ENTITY_TYPE_P',
 'OFFICIAL_MAIL_RECEIVER',
 'COUNT_NPO_OR_OTHER',
 'CURRENT_STATUS',
 'EFFECTIVE_DATE',
 'UPDATE_DATETIME',
 'USE_CODE',
 'USE_STATUS',
 'NUMBER_OF_RESIDENCES',
 'SEPERATELY_OWNED',
 'USE_POPULATION',
 'USE_POPULATION_PEOPLE',
 'ESTIMATED_USE_PER_PERSON',
 'USE_POPULATION_STOCK',
 'TYPE_OF_STOCK',
 'AREA_FOR_INCI_IRRIGATION',
 'USE_NET_ACREAGE',
 'USE_GROSS_ACREAGE',
 'USE_DIRECT_DIV_ANNUAL_AMOUNT',
 'USE_DIRECT_DIVERSION_RATE',
 'USE_DIRECT_DIV_RATE_UNITS',
 'POU_DEVELOPMENT_STATUS',
 'DIRECT_DIV_SEASON_START',
 'DIRECT_DIV_SEASON_END',
 'USE_STORAGE_AMOUNT',
 'STORAGE_SEASON_START',
 'STORAGE_SEASON_END',
 'SEASON_DIRECT_DIV_RATE',
 'SEASON_STORAGE_AMOUNT',
 'SEASON_DIRECT_DIV_AA',
 'DIRECT_DIV_SEASON_STATUS',
 'COLLECTION_SEASON_STATUS',
 'USE_COUNT',
 'POD_NUMBER',
 'POD_ID',
 'POD_STATUS',
 'SOURCE_TYPE',
 'POD_NAME',
 'POD_TYPE',
 'DIVERSION_WORKS_STATUS',
 'STREAM_CLASSIFICATION',
 'DIRECT_DIV_AMOUNT',
 'DIRECT_DIVERSION_RATE',
 'DIRECT_DIV_RATE_UNIT',
 'STORAGE_AMOUNT',
 'DIVERSION_RATE_TO_OFF_STREAM',
 'OFF_STO_DIV_RATE_UNIT',
 'POD_LAST_UPDATE_DATE',
 'POD_COUNT',
 'APPL_ID',
 'OBJECTID',
 'POD_NUMBER_GIS',
 'HAS_OPOD',
 'APPL_POD',
 'POD_ID_GIS',
 'COUNTY',
 'PARCEL_NUMBER',
 'SP_ZONE',
 'DIVERSION_SITE_NAME',
 'NORTH_COORD',
 'EAST_COORD',
 'LATITUDE',
 'LONGITUDE',
 'QUARTER_QUARTER',
 'QUARTER',
 'SECTION_CLASSIFIER',
 'SECTION_NUMBER',
 'TOWNSHIP_NUMBER',
 'TOWNSHIP_DIRECTION',
 'RANGE_NUMBER',
 'RANGE_DIRECTION',
 'MERIDIAN',
 'LOCATION_METHOD',
 'SPECIAL_USE_AREA',
 'SOURCE_NAME',
 'TRIB_DESC',
 'WATERSHED',
 'HUC_12_NUMBER',
 'HUC_12_NAME',
 'HUC_8_NUMBER',
 'HUC_8_NAME',
 'QUAD_MAP_NAME',
 'QUAD_MAP_NUMBER',
 'PERMIT_PERMIT_ID',
 'PERMIT_ORIGINAL_ISSUE_DATE',
 'COMPLETE_CONSTRUCTION_DATE',
 'COMPLETE_APPLIC_WATER_DATE',
 'LICENSE_LICENSE_ID',
 'LICENSE_ORIGINAL_ISSUE_DATE',
 'WATER_RIGHT_DESCRIPTION',
 'PROGRAM_UNIT',
 'LICENSE_REQUEST_TYPE',
 'LICENSE_REQUESTED_DATE',
 'INSPECTION_DATE',
 'REPORT_DATE',
 'OFFER_SENT_DATE',
 'ACCEPTED_OFFER_DATE',
 'PETITION_ID',
 'PETITION_TYPE',
 'PETITION_STATUS_TYPE',
 'DATE_RECEIVED',
 'DATE_COMPLETED',
 'PET_LAST_UPDATE_DATE',
 'NUM_OF_PETITIONS',
 'ENF_CASE_NUMBER',
 'ENF_CASE_START_DATE',
 'ENF_CASE_CLOSURE_DATE',
 'ENF_CASE_COUNTY',
 'NUMBER_OF_ENFORCEMENT_CASE']

In [8]:
print ("Directly mapped columns")

destCols=['WaterSourceName', 'WaterSourceTypeCV']
srsCols=['SOURCE_NAME', 'SOURCE_TYPE']

outdf100[destCols] = df100[srsCols]

Directly mapped columns

In [9]:
print("Hard coded ...")
outdf100.WaterQualityIndicatorCV = "Fresh"

outdf100.loc[outdf100['WaterSourceName']=='','WaterSourceName'] = "Unspecified"
outdf100.loc[outdf100['WaterSourceTypeCV']=='','WaterSourceTypeCV'] = "Unknown"

Hard coded ...

In [10]:
print("Dropping duplicates...")

print(len(outdf100.index))
outdf100 = outdf100.drop_duplicates(subset=['WaterSourceName']) #,'WaterQualityIndicatorCV'
outdf100 = outdf100.reset_index(drop=True)
print(len(outdf100.index))

outdf100

Dropping duplicates...
57736
8619

,WaterSourceUUID,WaterSourceNativeID,WaterSourceName,WaterSourceTypeCV,WaterQualityIndicatorCV,GNISFeatureNameCV,Geometry
0,NaN,NaN,Unspecified,Unknown,Fresh,NaN,NaN
1,NaN,NaN,LAKE DOMINGO,Surface,Fresh,NaN,NaN
2,NaN,NaN,ICY SPRING NO 2,Unknown,Fresh,NaN,NaN
3,NaN,NaN,SACRAMENTO RIVER,Unknown,Fresh,NaN,NaN
4,NaN,NaN,SAN JOAQUIN RIVER,Unknown,Fresh,NaN,NaN
...,...,...,...,...,...,...,...
8614,NaN,NaN,POD 8,Surface,Fresh,NaN,NaN
8615,NaN,NaN,POD 9,Surface,Fresh,NaN,NaN
8616,NaN,NaN,POD 10,Surface,Fresh,NaN,NaN
8617,NaN,NaN,POD 11,Surface,Fresh,NaN,NaN
8618,NaN,NaN,East Fork Russian River,Surface,Fresh,NaN,NaN

In [11]:
print ("Water source native id and UUID")

#9.12.19 Adel: For water sources table, how about we do an incremental ID? like 1, 2, 3 etc?
outdf100 = outdf100.reset_index(drop=True)
outdf100['WaterSourceNativeID'] = range(1, len(outdf100.index) + 1)

print("Adding UUID...")
outdf100['WaterSourceUUID'] = outdf100.apply(lambda row: 
                                        "_".join(["CA", str(row['WaterSourceNativeID'])]), axis=1)

outdf100 = outdf100.replace(np.nan, '')

outdf100

Water source native id and UUID
Adding UUID...

,WaterSourceUUID,WaterSourceNativeID,WaterSourceName,WaterSourceTypeCV,WaterQualityIndicatorCV,GNISFeatureNameCV,Geometry
0,CA_1,1,Unspecified,Unknown,Fresh,,
1,CA_2,2,LAKE DOMINGO,Surface,Fresh,,
2,CA_3,3,ICY SPRING NO 2,Unknown,Fresh,,
3,CA_4,4,SACRAMENTO RIVER,Unknown,Fresh,,
4,CA_5,5,SAN JOAQUIN RIVER,Unknown,Fresh,,
...,...,...,...,...,...,...,...
8614,CA_8615,8615,POD 8,Surface,Fresh,,
8615,CA_8616,8616,POD 9,Surface,Fresh,,
8616,CA_8617,8617,POD 10,Surface,Fresh,,
8617,CA_8618,8618,POD 11,Surface,Fresh,,
8618,CA_8619,8619,East Fork Russian River,Surface,Fresh,,

In [12]:
#write out
outdf100.to_csv(out_put, index=False, encoding = "utf-8")
print("Done watersources")

Done watersources